name: bike
favicon: null
layout_spectrum: 0.36330682085826993
typography_spectrum: 0.4579504681751132
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.880348646081984
  lightness: 0.6665789452381432
  saturation: 0.4080930727068335
  rhythmicContrast: 0.8848080376628786
purpose: []
